machine:
  docker_layer_caching: true  

version: 2
references:
  # We will define reusable references here
jobs:
  
  # Build
  # -------------------------------------------------------------->

  build_dashboard:
    working_directory: ~/project/datavent/dashboard
    docker:
      - image: circleci/node:9.8.0
    steps:
      - checkout:
          path: ~/project
      - run:
          name: File system orientation
          command: pwd && ls
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages with npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
            
  # Test
  # -------------------------------------------------------------->

  test_dashboard:
    working_directory: ~/project/datavent/dashboard
    docker:
      - image: circleci/node:9.8.0
    steps:
      - checkout:
          path: ~/project
      - run:
          name: File system orientation
          command: pwd && ls
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Run linting
          command: npm lint
      - run: 
          name: Run tests
          command: npm test

  # Deploy
  # -------------------------------------------------------------->

  deploy:
    docker:
      - image: circleci/node:9.8.0
    steps:
      - checkout
      - run:
          name: File system orientation
          command: pwd && ls
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install flutter tools
          command: npm install -g firebase-tools
      - run:
          name: Deploy dashboard to firebase hosting
          command: cd datavent/dashboard/ && firebase deploy --token "$FIREBASE_DEPLOY_TOKEN"
      - run:
          name: Deploy api to firebase functions
          command: cd datavent/api/ && firebase deploy --only functions
      
workflows:
  version: 2
  workflow:
    jobs:
      - build_dashboard
      - test_dashboard:
          requires:
            - build_dashboard
          filters:
            branches:
              only:
                - dev
                - /feature-.*/
      # - test_functions:
      #     requires:
      #       - 
      - deploy:
          requires:
            - build_dashboard
            - test_dashboard
          filters:
            branches:
              only: master