

version: 2
references:
  # We will define reusable references here
jobs:
  # Build debug APK for unit tests and an instrumented test APK
  build:
    working_directory: /home/circleci/project/datavent/dashboard
    docker:
      - image: circleci/node:9.8.0
    steps:
      - checkout
      - run:
          name: File system orientation
          command: pwd && ls
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages with npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  test_dev:
    working_directory: /home/circleci/project/datavent/dashboard
    docker:
      - image: circleci/node:9.8.0
    steps:
      - checkout
      - run:
          name: File system orientation
          command: pwd && ls
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Run unit tests
          command: npm test

  deploy:
    docker:
      - image: circleci/node:9.8.0
    steps:
      - checkout
      - run:
          name: Install flutter tools
          command: npm install -g firebase-tools
      - run:
          name: Deploy dashboard to firebase hosting
          command: firebase deploy --token "$FIREBASE_DEPLOY_TOKEN"
      

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test_dev:
          filters:
            branches:
              only:
                - dev
                - /feature-.*/
      - deploy:
          requires:
            - build
            - test_dev
          filters:
            branches:
              only: master